<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2014  Mageho (http://www.mageho.com)
 * @version      Release: 1.0.8.2
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php $hash = unserialize($this->getInfo()->getAdditionalData()); ?>
<?php $hlpr = Mage::helper('atos'); ?>
<div id="atos-logo">&nbsp;</div>

<p><strong><?php echo $this->getMethod()->getTitle(); ?></strong></p>

<ul class="messages">
	<?php if (isset($hash['response_code'])): ?>
		<?php if ($hash['response_code'] == '00'): ?>
	    <li class="success-msg"><?php echo $hlpr->__('Payment accepted by Atos'); ?></li>
	    <?php else: ?>
	    <li class="warning-msg"><?php echo $hlpr->__('Customer was rejected by Atos'); ?></li>
	    <?php endif; ?>
    <?php else: ?>
    <li class="warning-msg"><?php echo $hlpr->__('The customer left without paying'); ?></li>
    <?php endif; ?>
</ul>