<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2014  Mageho (http://www.mageho.com)
 * @version      Release: 1.0.8.2
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php $_code = $this->getMethodCode(); ?>
<?php $_paymentMeans = $this->getPaymentMeans(); ?>
<?php if ($_paymentMeans): ?>
<fieldset id="payment_form_<?php echo $_code; ?>" class="form-list" style="display:none">
    <div class="atos-select-cards">
    	<p class="choc"><?php echo $this->__('Select a credit card'); ?></p>
        <ol>
            <?php foreach($_paymentMeans as $key => $value): ?>
            <li>
               <input type="radio" name="payment[atos_several_payment_means]" value="<?php echo $key; ?>" id="<?php echo $value['id']; ?>" class="atos_cc validate-one-required-by-name" <?php if ($this->getSelectedMethod() == $key): ?>checked="checked"<?php endif; ?> />
               <label for="<?php echo $value['id']; ?>"><img src="<?php echo $value['src']; ?>" alt="<?php echo $value['alt']; ?>" /></label>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="atos-cms-block"><?php echo $this->getCmsBlock(); ?></div>
</fieldset>
<?php endif; ?>