<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2014  Mageho (http://www.mageho.com)
 * @version      Release: 1.0.8.2
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
?>
<?php $hash = unserialize($this->getInfo()->getAdditionalData()); ?>
<?php $hlpr = Mage::helper('atos'); ?>

<div id="atos-logo">&nbsp;</div>

<p><strong><?php echo $this->getMethod()->getTitle(); ?></strong></p>

<?php if (isset($hash) && !empty($hash)): ?>
<ul class="messages">
	<?php if ($hash['response_code'] == '00'): ?>
	<li class="success-msg"><?php echo $hlpr->__('Payment accepted by Atos'); ?></li>
	<?php else: ?>
	<li class="warning-msg"><?php echo $hlpr->__('Customer was rejected by Atos'); ?></li>
	<?php endif; ?>
</ul>

<?php
/*
 * Details de la transaction
 */
?>
<?php $return = Mage::getSingleton('atos/api_response')->paymentN($hash); ?>
<div class="grid">
	<table class="atowpseveral">
		<thead>
	    	<tr class="headings">
	        	<th><?php echo $hlpr->__('Credit Card'); ?></th>
	            <th><?php echo $hlpr->__('Payment Informations'); ?></th>
	            <th><?php echo $hlpr->__('Payment Due Dates'); ?></th>
	        </tr>
	    </thead>
		<tbody>
	    	<tr>
	        	<td class="payment-means first"><img src="<?php echo $this->getCreditCardImgSrc(strtolower($hash['payment_means'])); ?>" alt="<?php echo $hash['payment_means']; ?>" /></td>
	            <td class="payment-infos">
	                <ul>
	                    <li><?php echo $hlpr->__('Number of monthly') . ' : ' . $return['payment_n']; ?></li>
	                    <li><?php echo $hlpr->__('Debit every %d days', $return['period']); ?></li>
	                    <li><?php echo $hlpr->__('First debit') . ' : ' . Mage::getSingleton('atos/api_response')->formatAmount($return['initial_amount']); ?></li>
	                </ul>
	            </td>
	            <td class="payment-due-dates last">
	            	<ol>
						<?php foreach ($return['payment_due_dates'] as $date): ?>
	                    <li><?php echo $date; ?></li>
	                    <?php endforeach; ?>
	                </ol>
	            </td>
	        </tr>	
	    </tbody>
	</table>
</div>
<?php else: ?>
<ul class="messages">
	<li class="warning-msg"><?php echo $hlpr->__('The customer left without paying'); ?></li>
</ul>
<?php endif; ?>