<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2014  Mageho (http://www.mageho.com)
 * @version      Release: 1.0.8.3
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
/* <![CDATA[ */
    function generateAtosFiles() 
    {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method: 'get',
		    requestHeaders: {Accept: 'application/json'},
            onSuccess: function(transport) {
            	var json = transport.responseText.evalJSON(true);
		        $('atos_button_container').update(json.message);
            }
        });
        return false;
    }
/* ]]> */
</script>

<div id="atos_button_container">
	<?php echo $this->getButtonHtml() ?>
</div>